### ISSUE TITLE
Data not recorded

### ISSUE THREAD

**Issue by ryanbuiltthat** [sputlytics/sputlytics#10]
Hello,

I installed sputlytics use the one-click heroku setup and all seemed to go fine except no data is being recorded. I can verify the domains within the settings page of the app, i can see the domains in the MongoDB but no data is pushed to the app, or if it is, it's not saved to the DB. Any way to troubleshoot this I'm not seeing any console errors.

**Comment by caio-ribeiro-pereira** [comment]
Hi Ryan, our project is not ready yet to use it fine.
And we are working on to simplify the documentation and to release a beta
version soon.

Did you added the sputlytics tracking code? Is there any error showing this
script?

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by caio-ribeiro-pereira** [comment]
This tracking code is available into Settings page and you need to add this tracking code into the website you've registered.  

Regards,
Caio Ribeiro Pereira
Developer, blogger and writter
About: http://crpwebdev.com
Blog: http://udgwebdev.com

**Comment by caio-ribeiro-pereira** [comment]
@ryanbuiltthat hi again! I fix the bug, our agent.js (https://github.com/sputlytics/sputlytics-agent) did'nt treat the "/" in the end of a domain, so you probably are using this kind of snippet code:

``` javascript
spa("init", {domain: "https://mydomain.herokuapp.com/", clientKey: "XXXX"});
spa("pageview");
```

and because of `https://mydomain.herokuapp.com/` all requests were doing `//ping` into the server, instead `/ping`.

I just fixed this bug (https://github.com/sputlytics/sputlytics-agent/commit/8796997f40bfab551e7c446f4761f17fcc9dc218), to use a domain with or without `/` in the end of domain string, so soon you will can test our sputlytics server.

Thank you for helping us!

**Comment by ryanbuiltthat** [comment]
Ahhh seems to be working great! Thanks! I'm trying to add more and more metrics for my meteor apps, almost like Kadira but without having to pay so much :) if I get my server metrics working with your dashboard I'll send you a PR

**Comment by caio-ribeiro-pereira** [comment]
Nice! It's good to have early adopters using our project! Thank you for that! We are working to make the dashboard fasters, because the mongo observer is too slow, and probably we will remove this to increase the performance. Anyway, feel free to send PR for us! See ya!
